#!/bin/bash
set -e
echo "Installing Homebrew..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo "Restoring packages..."
brew install abseil
brew install ack
brew install ammonite-repl
brew install ampl-mp
brew install ant
brew install antlr
brew install aom
brew install arduino-cli
brew install aribb24
brew install assimp
brew install audiofile
brew install augeas
brew install auto-scaling
brew install autoconf
brew install automake
brew install avian
brew install aws-cfn-tools
brew install bash-completion
brew install bazelisk
brew install bdw-gc
brew install berkeley-db
brew install berkeley-db@5
brew install bloop
brew install boost
brew install brew-cask-completion
brew install brotli
brew install bullet
brew install bundler-completion
brew install bwm-ng
brew install c-ares
brew install ca-certificates
brew install cairo
brew install certbot
brew install certifi
brew install cffi
brew install cjson
brew install clingo
brew install cloc
brew install cmake
brew install console_bridge
brew install cowsay
brew install cppzmq
brew install cryptography
brew install cscope
brew install ctags
brew install d-bus
brew install dartsim
brew install dav1d
brew install dbus
brew install dialog
brew install diff-so-fancy
brew install dirmngr
brew install docker-machine
brew install docker-machine-driver-xhyve
brew install dotnet@8
brew install double-conversion
brew install doxygen
brew install dpkg
brew install ec2-api-tools
brew install eigen
brew install elasticsearch
brew install emacs
brew install emacs-mac
brew install exiftags
brew install exiftool
brew install expat
brew install fakeroot
brew install fcl
brew install ffmpeg
brew install flac
brew install flann
brew install fmt
brew install fontconfig
brew install freeimage
brew install freetype
brew install frei0r
brew install fribidi
brew install fuse-emulator
brew install fzf
brew install gazebo11
brew install gcc
brew install gcc48
brew install gcc@4.8
brew install gd
brew install gdbm
brew install gdk-pixbuf
brew install gettext
brew install ghostscript
brew install giflib
brew install git
brew install git-town
brew install giter8
brew install glew
brew install glib
brew install gmp
brew install gmp4
brew install gmp@4
brew install gnu-getopt
brew install gnu-tar
brew install gnupg
brew install gnupg2
brew install gnutls
brew install go
brew install gource
brew install gpatch
brew install gpg-agent
brew install gpgme
brew install gpsd
brew install gradle
brew install gradle-completion
brew install graphite2
brew install graphviz
brew install grc
brew install gringo
brew install gts
brew install guile
brew install harfbuzz
brew install haskell-stack
brew install hdf5
brew install helm
brew install highway
brew install hunspell
brew install hwloc
brew install icu4c
brew install icu4c@76
brew install idris
brew install iftop
brew install ignition-cmake2
brew install ignition-common3
brew install ignition-fuel-tools4
brew install ignition-math6
brew install ignition-msgs5
brew install ignition-tools
brew install ignition-transport8
brew install imagemagick
brew install imath
brew install ipopt
brew install isl
brew install isl011
brew install isl@0.11
brew install jansson
brew install jasper
brew install jbig2dec
brew install jemalloc
brew install jenv
brew install jpeg-turbo
brew install jpeg-xl
brew install jq
brew install jsoncpp
brew install k9s
brew install kubernetes-cli
brew install lame
brew install lazygit
brew install leptonica
brew install libaec
brew install libarchive
brew install libass
brew install libassuan
brew install libavif
brew install libb2
brew install libbluray
brew install libcbor
brew install libccd
brew install libde265
brew install libdeflate
brew install libev
brew install libevent
brew install libffi
brew install libfido2
brew install libgcrypt
brew install libgpg-error
brew install libheif
brew install libidn
brew install libidn2
brew install libksba
brew install liblinear
brew install liblqr
brew install libmaxminddb
brew install libmd
brew install libmicrohttpd
brew install libmng
brew install libmpc
brew install libmpc08
brew install libmpc@0.8
brew install libnghttp2
brew install libogg
brew install libomp
brew install libpng
brew install libraw
brew install librist
brew install librsvg
brew install libsamplerate
brew install libsmi
brew install libsndfile
brew install libsodium
brew install libsoxr
brew install libspectrum
brew install libssh
brew install libssh2
brew install libtar
brew install libtasn1
brew install libtermkey
brew install libtiff
brew install libtool
brew install libunibreak
brew install libunistring
brew install libusb
brew install libuv
brew install libvidstab
brew install libvmaf
brew install libvorbis
brew install libvpx
brew install libvterm
brew install libx11
brew install libxau
brew install libxcb
brew install libxdmcp
brew install libxext
brew install libxml2
brew install libxrender
brew install libyaml
brew install libzip
brew install libzzip
brew install little-cms2
brew install llvm
brew install lpeg
brew install lua
brew install lua-language-server
brew install luajit
brew install luv
brew install lz4
brew install lzo
brew install m4
brew install macvim
brew install marksman
brew install maven
brew install maven-completion
brew install mbedtls
brew install md4c
brew install mercurial
brew install mitmproxy
brew install mpdecimal
brew install mpfr
brew install mpfr2
brew install mpfr@2
brew install mpg123
brew install msgpack
brew install mutt
brew install mysql
brew install ncurses
brew install neovim
brew install neovim-dot-app
brew install netpbm
brew install nettle
brew install nghttp2
brew install ninja
brew install nlopt
brew install nmap
brew install node
brew install npth
brew install nvm
brew install ocaml
brew install octomap
brew install ode
brew install ogre1.9
brew install oniguruma
brew install opam
brew install open-scene-graph
brew install openblas
brew install opencore-amr
brew install openexr
brew install openjdk
brew install openjpeg
brew install openldap
brew install openssl@1.1
brew install openssl@3
brew install openvpn
brew install opus
brew install ossp-uuid
brew install p11-kit
brew install pango
brew install pass
brew install pcre
brew install pcre2
brew install pdftohtml
brew install perl
brew install phantomjs
brew install pinentry
brew install pip-completion
brew install pixman
brew install pkcs11-helper
brew install pkg-config
brew install pnpm
brew install potrace
brew install protobuf
brew install protobuf@21
brew install pstree
brew install pwgen
brew install pycparser
brew install pyenv
brew install pyenv-virtualenv
brew install pygame
brew install python
brew install python-certifi
brew install python-cryptography
brew install python-packaging
brew install python@3.10
brew install python@3.11
brew install python@3.12
brew install python@3.13
brew install qrencode
brew install qt
brew install qt5
brew install qt@5
brew install qwt-qt5
brew install rails-completion
brew install rake-completion
brew install rav1e
brew install rbenv
brew install rbenv-bundle-exec
brew install rbenv-ctags
brew install rbenv-use
brew install rbenv-whatis
brew install readline
brew install rename
brew install ripgrep
brew install rubberband
brew install ruby
brew install ruby-build
brew install ruby-completion
brew install ruby-install
brew install rust
brew install rustc-completion
brew install rustup
brew install rustup-init
brew install sbt
brew install scala
brew install scons
brew install sdformat9
brew install sdl
brew install sdl12-compat
brew install sdl2
brew install sdl2_image
brew install sevenzip
brew install shared-mime-info
brew install simbody
brew install six
brew install sloccount
brew install snappy
brew install spdlog
brew install speex
brew install speexdsp
brew install sqlite
brew install srt
brew install svt-av1
brew install tbb
brew install telepresence
brew install telnet
brew install tesseract
brew install texinfo
brew install the_silver_searcher
brew install theora
brew install tig
brew install tika
brew install tinyxml1
brew install tinyxml2
brew install tmux
brew install tmuxinator
brew install tofrodos
brew install tokyo-cabinet
brew install tomcat
brew install tree
brew install tree-sitter
brew install typesafe-activator
brew install unbound
brew install unibilium
brew install unison-language
brew install urdfdom
brew install urdfdom_headers
brew install utf8proc
brew install vagrant-completion
brew install vcpkg
brew install vcprompt
brew install webp
brew install wget
brew install wireshark
brew install wrk
brew install x264
brew install x265
brew install xorgproto
brew install xvid
brew install xz
brew install yazi
brew install youtube-dl
brew install z3
brew install zeromq
brew install zimg
brew install zlib
brew install zstd
brew install --cask adoptopenjdk
brew install --cask aerospace
brew install --cask barrier
brew install --cask font-symbols-only-nerd-font
brew install --cask ghostty
brew install --cask insomnia
brew install --cask keybase
brew install --cask macvim
brew install --cask pants
brew install --cask rio
brew install --cask vimr
brew install --cask vlc
brew install --cask wezterm
